- virtme/commands/run.py
Catch and ignore ENOTTY exceptions from os.get_terminal_size().
Signed-off-by: Zev Weiss <zev@bewilderbeest.net>
> virtme-run: Handle non-tty stdout

- setup.py
Related issue: #21 
`setup.py` doesn't copy the necessary bash files from **virtme/guest** folder
to the installed folder. This will make `virtme-run` to fail when running with` --kimg` argument, for example.
This problem can be solved if we transform **virtme/guest** folder, which only have bash
scripts, into a python package via adding a **__init__.py** file and instructing
`setup.py` that _virtme.guest_ is a package and we will need its contents as
package data.
This idea was based on the `setuptools` docs advice:
https://setuptools.readthedocs.io/en/latest/setuptools.html#non-package-data-files
This PR has the related contribution of @ezequielgarcia, which improved the requirements for `setup.py` script.
> Transform virtme/guest into a Python package

- virtme/guest/virtme-init
Automatically mount cgroup v2 filesystem under /sys/fs/cgroup/unified as
it seems a pretty standard place and tools relying on cgroupv2 are
expecting to find this filesystem mounted there.
Signed-off-by: Andrea Righi <righi.andrea@gmail.com>
> virtme-init: mount cgroup v2

- virtme/guest/virtme-init
Using a shared folder like --rwdir=/run/output=/path/on/host fails,
since the mountpoint under /run does not exist. Create the mountpoint
if it doesn't exist. Also abort the script if mounting fails.
> virtme-init: create mountpoints if they don't exist

- virtme/guest/virtme-init
In my environment, /dev is available via the 9p root mount, and
therefore virtme-init does not mount a fresh devtmpfs. This means
that udevd later is unable to generate new entries for /dev/vport*.
Using --script-sh or --script-exec therefore fails.
Instead, use findmnt to check whether /dev is automounted by the
current kernel.
> virtme-init: use findmnt to detect /dev mount

- virtme/guest/virtme-init
In recent distro (i.e., Ubuntu) resolv.conf is a symlink to
/run/systemd/resolve/stub-resolv.conf that is not visible by the guest.
This results in a failure when trying to initialize this file.
Make sure to resolve the symlink first and initialize the actual file
with an empty file before trying to rewrite its content.
Signed-off-by: Andrea Righi <andrea.righi@canonical.com>
> virtme-init: correctly initialize resolv.conf under ubuntu

- virtme/guest/virtme-init
I've re-used the bridge of libvirtd. A vm gets it lease by the 3rd dhcp requests.
Log of udhcpc without this patch.
udhcpc: sending discover
udhcpc: no lease, failing
Log of udhcpc with this patch.
udhcpc: started, v1.27.2
udhcpc: sending discover
udhcpc: sending discover
udhcpc: sending select for 192.168.123.76
udhcpc: lease of 192.168.123.76 obtained, lease time 3600
This patch removes the '-t' arg to use the default retries which is 3.
Signed-off-by: Jian Wen <wenjianhn@gmail.com>
> Using udhcpc default retries

- virtme/modfinder.py
openSUSE and SLE don't have modprobe in the user's PATH, so check
/usr/sbin too. With this patch applied, an ordinary user can execute
virtme-run --installed-kernel
Without the need to be root in openSUSE/SLE.
Signed-off-by: Marcos Paulo de Souza <mpdesouza@suse.com>
> modfinder.py: Check if modprobe is the PATH of the user

- virtme/mkinitramfs.py
This is on a somewhat related note to https://github.com/amluto/virtme/pull/13 in aiming to broaden the range of busybox packaging styles virtme can support.
Void Linux offers both statically and dynamically linked versions of busybox in its package repos.  Without #13, virtme requires a static build, but unfortunately for virtme Void's busybox-static package installs a binary called `busybox.static` (as opposed to the `busybox-static` virtme currently searches for).
So either #13 or this would address the immediate "virtme doesn't work on my distro" problem, though I think there could still potentially be value in both (would support either version of the package instead of requiring the static one).
> More potential paths for busybox executable

- virtme/commands/configkernel.py
If KBUILD_OUTPUT is defined, and if it's a directory, write the .config file in location defined.
Fixes: #24 
Signed-off-by: Marcos Paulo de Souza <marcos.souza.org@gmail.com>
> commands/configkernel.py: Check KBUILD_OUTPUT environment variable

- virtme/commands/run.py
- virtme/mkinitramfs.py
Error reportage in the dummy modprobe script and a misdirected check in `--disk` argument validation.
> Miscellaneous small fixes

- virtme/commands/run.py
virtme-run hadn't been passing .virtme_mods as the root directory to find_modules_from_install(), causing it to not find any modules.
> Fix module-finding in $KDIR/.virtme_mods

- bin/virtme-prep-kdir-mods
- setup.py
- virtme/commands/run.py
- virtme/guest/virtme-init
- virtme/modfinder.py
When --kdir is provided there's not an easy and automated way to use
kernel modules from the guest.
A possible solution could be to install all the modules inside the
kernel build directory (argument of --kdir) inside a temporary directory
.tmp_moddir/ as following:
$ make modules_install INSTALL_MOD_DIR=.tmp_moddir
In this way if .tmp_moddir is found the guest can use the kernel modules
from this directory, otherwise fallback to the old behavior and do not
provide an automated way to access the kernel modules.
TODO: document this .tmp_moddir/ directory somewhere.
Signed-off-by: Andrea Righi <andrea.righi@canonical.com>
> virtme-run: provide a way to support modules with --kdir

- setup.py
- virtme-mkinitramfs
- virtme/commands/mkinitramfs.py
While trying to create an initrd file using virtme-mkinitramfs, I found this script is not currently working, and is neither being installed like virtme-run and virtme-configkernel.
Let me know if I misunderstood the purpose of the tool or if the code needs some polishment.
> Make virtme-mkinitramfs great again

- bin/virtme-prep-kdir-mods
openSUSE have depmod in /usr/sbin, and this directory is not present in
user's default path.
Fixes: 3a65e4b514c0 ("Add virtme-prep-kdir-mods and support it")
Signed-off-by: Marcos Paulo de Souza <marcos.souza.org@gmail.com>
> virtme-prep-kdir-mods: Check if depmod is in the user's PATH

- virtme/mkinitramfs.py
In currentl Tumbleweed, using busybox dynamic linked does not work. For
now let's check if we have busybox static first.
Fix: #51
Signed-off-by: Marcos Paulo de Souza <mpdesouza@suse.com>
> mkinitramfs.py: Search for busybox{.,-}static first

- virtme-configkernel
- virtme-mkinitramfs
- virtme-run
This is helpful when system version of python3 is too old for running new syntax used in the virtme scripts. And newer version of python3 can be compiled and installed in user local directory.
> Make scripts PATH friendly for searching python3

- bin/virtme-prep-kdir-mods
Existence of modules.order is checked twice.
Signed-off-by: Pavel Tatashin <pasha.tatashin@soleen.com>
> remove duplicated check from virtme-prep-kdir-mods

- virtme/commands/run.py
This new argument will be responsible for adding a virtio-blk devices,
instead of the virtio-scsi already being handled by --disk.
Notable changes from --disk:
* --blk-disks accepts multiple disks separeted by comma
* Each disk don't have a proper name as in SCSI, but instead we add an
index, starting from 0, in the order the disks are defined. For
example, --blk-disks "file1,file2", will create virtio-virtme_disk_blk0
virtio-virtme_disk_blk1 in /dev/disks/by-id.
Signed-off-by: Marcos Paulo de Souza <mpdesouza@suse.com>
> run.py: Add blk-disks argument

- virtme/commands/run.py
Introduce a --cpu argument to virtme-run, so we can set qemu's -smp commandline
parameter.
Signed-off-by: Johannes Thumshirn <johannes.thumshirn@wdc.com>
> run.py: introduce '--cpus' argument

- virtme/commands/configkernel.py
Kernel commit 911a91c39cab ("kconfig: rename silentoldconfig to
syncconfig"), so also rename the updatetarget in virtme to reflect the
change.
Signed-off-by: Marcos Paulo de Souza <mpdesouza@suse.com>
> virtme-configkernel: Fix --allnoconfig option

- virtme/guest/virtme-init
Trying to switch to any non-root user from a virtme environment returns
the following error:
su: Authentication failure
Populate dummy entries in /etc/shadow to allow switching to any user
defined in the system.
Signed-off-by: Andrea Righi <andrea.righi@canonical.com>
> virtme-init: generate dummy /etc/shadow

- virtme/architectures.py
When running virtme natively on a aarch64 host, we should use the same
version of GIC as the host. We also don't need to emulate a CPU. Instead
we can run on the host one.
Signed-off-by: Matthias Brugger <mbrugger@suse.com>
> aarch64: Fix aarch64 support

- virtme/commands/run.py
Newer qemu warns about a depcrecated readonly statement:
warning: short-form boolean option 'readonly' deprecated
Please use readonly=on instead
Fix this by using the correct readonly=on statement.
Signed-off-by: Matthias Brugger <mbrugger@suse.com>
> run.py: Fix deprecated qemu readonly statement
